[project]
name = "sakugaflow"
version = "0.10.0"
description = "AI-powered tool to boost FPS in anime, making 24fps scenes smoother by interpolating frames with Deep Learning."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "Apache-2.0" }

authors = [
  { name = "Alvaro Rodriguez" }
]

dependencies = [
  "ipykernel>=6.29.5",
  "torch>=2.6.0",
  "torchvision>=0.21.0",
  "torchaudio>=2.6.0",
  "opencv-python>=4.11.0.86",
  "pydantic>=2.10.6",
  "fire>=0.7.0",
  "saibyo>=0.11.1",
  "pyfiglet>=1.0.4",
  "wcwidth>=0.2.13",
  "typing_extensions>=4.5.0",
]

[dependency-groups]
format = ["ruff>=0.1.14"]
test = [
  "pytest>=7.4.4",
  "pytest-cov>=4.1.0"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
